import numpy as np
import matplotlib.pyplot as plt
import pylab

antonie_ANI = np.genfromtxt("/home/felipe/antonie_com_ANI_compilado.txt", delimiter="\t", names=["xan1","yan1"])
antonie_NOT = np.genfromtxt("/home/felipe/antonie_sem_ANI_compilado.txt", delimiter="\t", names=["xan2","yan2"])
archives_ANI = np.genfromtxt("/home/felipe/archives_com_ANI_compilado.txt", delimiter="\t", names=["xar1","yar1"])
archives_NOT = np.genfromtxt("/home/felipe/archives_sem_ANI_compilado.txt", delimiter="\t", names=["xar2","yar2"])
frontiers_ANI = np.genfromtxt("/home/felipe/frontiers_com_ANI_compilado.txt", delimiter="\t", names=["xfr1","yfr1"])
frontiers_NOT = np.genfromtxt("/home/felipe/frontiers_sem_ANI_compilado.txt", delimiter="\t", names=["xfr2","yfr2"])
ijsem_ANI = np.genfromtxt("/home/felipe/ijsem_com_ANI_compilado.txt", delimiter="\t", names=["xij1","yij1"])
ijsem_NOT = np.genfromtxt("/home/felipe/ijsem_sem_ANI_compilado.txt", delimiter="\t", names=["xij2","yij2"])
sam_ANI = np.genfromtxt("/home/felipe/sam_com_ANI_compilado.txt", delimiter="\t", names=["xsa1","ysa1"])
sam_NOT = np.genfromtxt("/home/felipe/sam_sem_ANI_compilado.txt", delimiter="\t", names=["xsa2","ysa2"])
todos_sp_nov_ANI = np.genfromtxt("/home/felipe/todos_sp_nov_com_ANI_compilado.txt", delimiter="\t", names=["xno1","yno1"])
todos_sp_nov_NOT = np.genfromtxt("/home/felipe/todos_sp_nov_sem_ANI_compilado.txt", delimiter="\t", names=["xno2","yno2"])
antonie_reclassificacao_ANI = np.genfromtxt("/home/felipe/antonie_reclassificacao_com_ANI_compilado.txt", delimiter="\t", names=["xanr1","yanr1"])
antonie_reclassificacao_NOT = np.genfromtxt("/home/felipe/antonie_reclassificacao_sem_ANI_compilado.txt", delimiter="\t", names=["xanr2","yanr2"])
archives_reclassificacao_NOT = np.genfromtxt("/home/felipe/archives_reclassificacao_sem_ANI_compilado.txt", delimiter="\t", names=["xarr2","yarr2"])
frontiers_reclassificacao_ANI = np.genfromtxt("/home/felipe/frontiers_reclassificacao_com_ANI_compilado.txt", delimiter="\t", names=["xfrr1","yfrr1"])
frontiers_reclassificacao_NOT = np.genfromtxt("/home/felipe/frontiers_reclassificacao_sem_ANI_compilado.txt", delimiter="\t", names=["xfrr2","yfrr2"])
ijsem_reclassificacao_ANI = np.genfromtxt("/home/felipe/ijsem_reclassificacao_com_ANI_compilado.txt", delimiter="\t", names=["xijr1","yijr1"])
ijsem_reclassificacao_NOT = np.genfromtxt("/home/felipe/ijsem_reclassificacao_sem_ANI_compilado.txt", delimiter="\t", names=["xijr2","yijr2"])
sam_reclassificacao_ANI = np.genfromtxt("/home/felipe/sam_reclassificacao_com_ANI_compilado.txt", delimiter="\t", names=["xsar1","ysar1"])
sam_reclassificacao_NOT = np.genfromtxt("/home/felipe/sam_reclassificacao_sem_ANI_compilado.txt", delimiter="\t", names=["xsar2","ysar2"])
todas_reclassificacoes_ANI = np.genfromtxt("/home/felipe/todas_reclassificacoes_com_ANI_compilado.txt", delimiter="\t", names=["xnor1","ynor1"])
todas_reclassificacoes_NOT = np.genfromtxt("/home/felipe/todas_reclassificacoes_sem_ANI_compilado.txt", delimiter="\t", names=["xnor2","ynor2"])
#print data["x"]

yan1 = np.cumsum(antonie_ANI["yan1"])
yan2 = np.cumsum(antonie_NOT["yan2"])
yar1 = np.cumsum(archives_ANI["yar1"])
yar2 = np.cumsum(archives_NOT["yar2"])
yfr1 = np.cumsum(frontiers_ANI["yfr1"])
yfr2 = np.cumsum(frontiers_NOT["yfr2"])
yij1 = np.cumsum(ijsem_ANI["yij1"])
yij2 = np.cumsum(ijsem_NOT["yij2"])
ysa1 = np.cumsum(sam_ANI["ysa1"])
ysa2 = np.cumsum(sam_NOT["ysa2"])
yno1 = np.cumsum(todos_sp_nov_ANI["yno1"])
yno2 = np.cumsum(todos_sp_nov_NOT["yno2"])
yanr1 = np.cumsum(antonie_reclassificacao_ANI["yanr1"])
yanr2 = np.cumsum(antonie_reclassificacao_NOT["yanr2"])
yarr2 = np.cumsum(archives_reclassificacao_NOT["yarr2"])
yfrr1 = np.cumsum(frontiers_reclassificacao_ANI["yfrr1"])
yfrr2 = np.cumsum(frontiers_reclassificacao_NOT["yfrr2"])
yijr1 = np.cumsum(ijsem_reclassificacao_ANI["yijr1"])
yijr2 = np.cumsum(ijsem_reclassificacao_NOT["yijr2"])
ysar1 = np.cumsum(sam_reclassificacao_ANI["ysar1"])
ysar2 = np.cumsum(sam_reclassificacao_NOT["ysar2"])
ynor1 = np.cumsum(todas_reclassificacoes_ANI["ynor1"])
ynor2 = np.cumsum(todas_reclassificacoes_NOT["ynor2"])

#print z
fig, ax = plt.subplots()
pylab.xlim([2007,2017])
pylab.ylim([0,10000])
plt.yscale('symlog')

myticks = [0,1,10,100,1000,10000]
ax.set_yticklabels(myticks)

ax.plot(antonie_ANI["xan1"], yan1, 'k', linestyle='-', marker='o', linewidth=2, label ='antonie with ANI')
ax.plot(antonie_NOT["xan2"], yan2, 'k', linestyle='--', marker='s', linewidth=2, label ='antonie without ANI')
ax.plot(archives_ANI["xar1"], yar1, 'b', linestyle='-', marker='o', linewidth=2, label ='archives with ANI')
ax.plot(archives_NOT["xar2"], yar2, 'b', linestyle='--', marker='s', linewidth=2, label ='archives without ANI')
ax.plot(frontiers_ANI["xfr1"], yfr1, 'r', linestyle='-', marker='o', linewidth=2, label ='frontiers with ANI')
ax.plot(frontiers_NOT["xfr2"], yfr2, 'r', linestyle='--', marker='s', linewidth=2, label ='frontiers without ANI')
ax.plot(ijsem_ANI["xij1"], yij1, 'm', linestyle='-', marker='o', linewidth=2, label ='ijsem with ANI')
ax.plot(ijsem_NOT["xij2"], yij2, 'm', linestyle='--', marker='s', linewidth=2, label ='ijsem without ANI')
ax.plot(sam_ANI["xsa1"], ysa1, 'g', linestyle='-', marker='o', linewidth=2, label ='sam with ANI')
ax.plot(sam_NOT["xsa2"], ysa2, 'g', linestyle='--', marker='s', linewidth=2, label ='sam without ANI')
#ax.plot(todos_sp_nov_ANI["xno1"], yno1, 'g', linestyle='-', marker='o', linewidth=2, label ='sp nov with ANI')
#ax.plot(todos_sp_nov_NOT["xno2"], yno2, 'g', linestyle='--', marker='s', linewidth=2, label ='sp nov without ANI')
#ax.plot(antonie_reclassificacao_ANI["xanr1"], yanr1, 'k4', linewidth=3, label ='antonie rec with ANI')
#ax.plot(antonie_reclassificacao_NOT["xanr2"], yanr2, 'ks', linewidth=3, label ='antonie rec without ANI')
#ax.plot(archives_reclassificacao_NOT["xarr2"], yarr2, 'kp', linewidth=3, label ='archives rec without ANI')
#ax.plot(frontiers_reclassificacao_ANI["xfrr1"], yfrr1, 'k*', linewidth=3, label ='frontiers rec with ANI')
#ax.plot(frontiers_reclassificacao_NOT["xfrr2"], yfrr2, 'kh', linewidth=3, label ='frontiers rec without ANI')
#ax.plot(ijsem_reclassificacao_ANI["xijr1"], yijr1, 'kH', linewidth=3, label ='ijsem rec with ANI')
#ax.plot(ijsem_reclassificacao_NOT["xijr2"], yijr2, 'k+', linewidth=3, label ='ijsem rec without ANI')
#ax.plot(sam_reclassificacao_ANI["xsar1"], ysar1, 'kx', linewidth=3, label ='sam rec with ANI')
#ax.plot(sam_reclassificacao_NOT["xsar2"], ysar2, 'kD', linewidth=3, label ='sam rec without ANI')
#ax.plot(todas_reclassificacoes_ANI["xnor1"], ynor1, 'kd', linewidth=3, label ='sp nov rec with ANI')
#ax.plot(todas_reclassificacoes_NOT["xnor2"], ynor2, 'k|', linewidth=3, label ='sp nov rec without ANI')

lgd = plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))
plt.savefig('/home/felipe/myplot.svg', bbox_extra_artists=(lgd,), bbox_inches='tight')
